## Connect to the database
context <- NewDataContext("<registered email>")

## Create a new Protocol
protocol <- context$insertProtocol("R protocol", "... my protocol document ...")

## Or a protocol load one via URI
protocol <- context$getObjectWithURI('<URI copied from Ovation application>')

## Get a reference to a Source and Epoch container (e.g. an EpochGroup)

source <- context$getObjectWithURI('ovation://1ce7d897-db87-4a66-aab9-65898e2cddc9/')
epochGroup <- context$getObjectWithURI('ovation://7271a95c-4b91-4e09-a48e-1cf510332ffb/')

## Insert a new Epoch
protocolParameters <- list(param1 = "value1", param2 = 3, param3 = "some text")
deviceParameters <- list() # Add device parameters here
inputSources = list(subject=source) # Map of input sources
outputSources - list() # No new sources generated by this Epoch
epoch <- epochGroup$insertEpoch(List2Map(inputSources), 
                                List2Map(outputSources),
                                Datetime(year=2013, month=7, day=6), 
                                Datetime(year=2013, month=7, day=7), 
                                protocol, 
                                List2Map(protocolParameters), 
                                List2Map(deviceParameters))

## Add a CSV measurement
measurement <- epoch$insertMeasurement("table1", # Measurement name
                                       Vector2Set(c("subject")), # Note same name as inputSources above
                                       Vector2Set(c("device1", "device2")), # Device(s) used to make measurement. Should be present (or added) in Experiment$getEquipmentSetup
                                       NewUrl("/path/to/example.csv"),
                                       "application/csv"
                                       )

# Wait (up to 60 minutes) for all uploads to finish
fs <- context$getFileService()
TimeUnit <- J("java.util.concurrent.TimeUnit")
Long <- J("java.lang.Long")
fs$waitForPendingUploads(as.integer(60), TimeUnit$MINUTES)
  

## Retrieve the DataFrame from measurement
# The pattern for downloading (if ncessary) and accessing the local cached copy of measurement's data
localFilePath <- measurement$getLocalDataPath()$get()

df <- read.csv(localFilePath)